### ISSUE TITLE
Not work in Xcod 7.0 beta

### ISSUE THREAD

**Issue by bagusflyer** [tristanhimmelman/AlamofireObjectMapper#12] opened 2015-07-04 04:34 UTC
Got the following error message:

> The following build commands failed:
	CompileSwift normal x86_64 /Users/Public/Test/Projects/TestProject/Carthage/Checkouts/AlamofireObjectMapper/AlamofireObjectMapper/AlmofireObjectMapper.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Any idea? Thanks

**Comment by pizthewiz** [comment] 2015-07-16 23:35
Duplicate of #9, AlamofireObjectMapper does not yet support Swift 2.0.

**Comment by tristanhimmelman** [comment] 2015-08-26 16:42
I have just created a branch with swift 2.0 support. See https://github.com/tristanhimmelman/AlamofireObjectMapper/tree/swift-2.0

**Closed** 2015-08-26 16:42 UTC
